alias gs="git status"
#git config --global alias.lol "log --graph --oneline --decorate --color --all"
alias gl="git log --graph --oneline --decorate --color --all"
alias ga="git add"
alias gc="git commit"
